do not call nmProcessSpec if Softsusy exits with non-zero exit code

diff --git a/run_nmssmtools.sh.in b/run_nmssmtools.sh.in
--- a/run_nmssmtools.sh.in
+++ b/run_nmssmtools.sh.in
@@ -38,5 +38,11 @@ if ! test -r "${slha_input_file}"; then
 fi
 
 ${BASEDIR}/softpoint.x leshouches < ${slha_input_file} > ${slha_output_file}
+
+if test $? -ne 0; then
+    echo "Warning: invalid point"
+    exit 1
+fi
+
 cp ${slha_output_file} ${NMSSMTOOLS_PATH}/main/slha_nmssm
 $(cd ${NMSSMTOOLS_PATH}/main/ && ./nmProcessSpec)
