clean up NMSSMTools interface
removing src/nmProcessSpec.f

diff --git a/softsusy_nmssmtools.x.in b/softsusy_nmssmtools.x.in
--- a/softsusy_nmssmtools.x.in
+++ b/softsusy_nmssmtools.x.in
@@ -18,13 +18,13 @@ if ! test -d "${NMSSMTOOLS_PATH}"; then
     exit 1
 fi
 
-if ! test -x "${NMSSMTOOLS_PATH}/main/nmProcessSpec"; then
-    echo "# Error: Cannot find ${NMSSMTOOLS_PATH}/main/nmProcessSpec"
+if ! test -x "${NMSSMTOOLS_PATH}/main/nmh_slhainp"; then
+    echo "# Error: Cannot find ${NMSSMTOOLS_PATH}/main/nmh_slhainp"
     echo "   Please run ./setup_nmssmtools.sh --nmssmtools-dir=/path/to/NMSSMTools --compile"
     exit 1
 fi
 
-nmssmtools_input_file="${NMSSMTOOLS_PATH}/main/slha_nmssm"
+nmssmtools_input_file="${NMSSMTOOLS_PATH}/main/inp"
 
 ${BASEDIR}/softpoint.x leshouches < /dev/stdin | tee ${nmssmtools_input_file}
 
@@ -33,36 +33,15 @@ if test $? -ne 0; then
     exit 1
 fi
 
-# check if nmProcessSpec or nmh_shlainp shall be used
-# @todo remove the following and always assume nmh_shlainp_on="yes"
-nmh_shlainp_on="`grep ATQ2 ${nmssmtools_input_file}`"
-if [ -z "${nmh_shlainp_on}" ] ; then
-    nmh_shlainp_on="yes"
-else
-    nmh_shlainp_on="no"
-fi
-
-# @todo remove if statement and keep only first block
-if test "x${nmh_shlainp_on}" = "xyes"; then
-    mv "${nmssmtools_input_file}" "`dirname ${nmssmtools_input_file}`/inp"
-    (cd ${NMSSMTOOLS_PATH}/main/ && ./nmh_slhainp)
-else
-    (cd ${NMSSMTOOLS_PATH}/main/ && ./nmProcessSpec)
-fi
+(cd ${NMSSMTOOLS_PATH}/main/ && ./nmh_slhainp)
 
 if test $? -ne 0; then
     echo "# Error: NMSSMTools could not calculate the decays"
     exit 1
 fi
 
-# @todo remove if statement and keep only first block
-if test "x${nmh_shlainp_on}" = "xyes"; then
-    decay_output_file="${NMSSMTOOLS_PATH}/main/decay"
-    omega_output_file="${NMSSMTOOLS_PATH}/main/omega"
-else
-    decay_output_file="${NMSSMTOOLS_PATH}/main/nmProcessSpec-decay"
-    omega_output_file="${NMSSMTOOLS_PATH}/main/nmProcessSpec-omega"
-fi
+decay_output_file="${NMSSMTOOLS_PATH}/main/decay"
+omega_output_file="${NMSSMTOOLS_PATH}/main/omega"
 
 if ! test -r "${decay_output_file}"; then
     echo "# Error: cannot open decay output file \"${decay_output_file}\""
